### ISSUE TITLE
nysed_activeinstitutions

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-data-recipes#3]
- [x] which csv? 
- [x] load into s3
- [ ] write build.py 
- [ ] write nysed_activeinstitutions.sql

https://eservices.nysed.gov/sedreports/list?id=1

**Comment by AmandaDoyle** [comment]
@SPTKL @baolingz 
Load 
All Institutions: Active Institutions with GIS coordinates and OITS Accuracy Code - Select by County
From https://eservices.nysed.gov/sedreports/list?id=1
Select: Bronx, Kings, Queens, New York, Richmond

**Comment by SPTKL** [comment]
```
WHEN inst_type_description = 'NON-PUBLIC SCHOOLS'
AND (prek::numeric+halfk::numeric+fullk::numeric+gr1::numeric+gr2::numeric+gr3::numeric+gr4::numeric+gr5::numeric+uge::numeric)>0
```
we no long have grade level info in the source data, need to find new ways to identify elementry/middle school/ high school

oh nevermind, we will do have a merge in the end

**Comment by SPTKL** [comment]
![image](https://user-images.githubusercontent.com/13207770/58184127-83c59b80-7c7e-11e9-906a-46753d7939e1.png)

**Comment by baolingz** [comment]
@SPTKL duplicate column names found in nysed_activeinstitutions
<img width="694" alt="Screen Shot 2019-06-04 at 12 06 15 PM" src="https://user-images.githubusercontent.com/31453240/58895618-53402180-86c2-11e9-94af-94b4552d6e8a.png">
