### ISSUE TITLE
nysomh_mentalhealth

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-data-recipes#5]
https://data.ny.gov/Human-Services/Local-Mental-Health-Programs/6nvr-tbv8
https://data.ny.gov/api/views/6nvr-tbv8/rows.csv?accessType=DOWNLOAD
- [x] s3 
- [x] build.py
- [x] .sql

**Comment by baolingz** [comment]
@SPTKL Review Request

**Comment by baolingz** [comment]
@SPTKL Review Request
