### ISSUE TITLE
usdot_airports

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-data-recipes#6]
https://www.arcgis.com/home/item.html?id=a36a509eab4e43b4864fb594a35b90d6

- [x] still need to figure out how to get the data
- [x] s3
- [ ] build.py
- [ ] .sql

**Comment by AmandaDoyle** [comment]
https://data-usdot.opendata.arcgis.com/datasets/airports-2?geometry=-75.97%2C40.406%2C-71.043%2C41.134

@SPTKL you can get the data as a shapefile from here
