### ISSUE TITLE
usnps_parks

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-data-recipes#9]
https://irma.nps.gov/DataStore/Reference/Profile/2225713

- [x] s3
- [x] .py
- [x] .sql

**Comment by SPTKL** [comment]
- original file is zipped shapefiles
- use gdal to convert to csv and create wkt_geometry

**Comment by baolingz** [comment]
Centroid need to be calculated.

**Comment by baolingz** [comment]
@SPTKL Review Request

**Comment by baolingz** [comment]
@SPTKL centroid has been added in sql, please review

**Comment by baolingz** [comment]
The URL changed, update the data recipe using the new URL:
https://irma.nps.gov/DataStore/DownloadFile/627620
